# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  push:
    tags:
      - '**'

jobs:
  call-ci-workflow:
    uses: oceanprotocol/contracts/.github/workflows/ci.yml@HEAD

  deploy:
    runs-on: ubuntu-latest
    needs: [call-ci-workflow]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Replace `.` with `_` in directory names
      run: |
        find artifacts -depth -type d -name '*.sol' -execdir bash -c 'mv -- "$1" "${1//.sol/_sol}"' bash {} \;
    - name: Create __init__.py files
      run: |
        find artifacts -type d -exec touch '{}'/__init__.py ';'
        find addresses -type d -exec touch '{}'/__init__.py ';'
    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
